name: frappuccino
description: A new Flutter project.
publish_to: "none"
homepage: "https://ysf-frappuccino.net/"
repository: "https://github.com/YumNumm/ysf-frappuccino"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.0
  flutter_web_plugins:
    sdk: flutter
  hooks_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
