name: frappuccino
description: A new Flutter project.
publish_to: "none"
homepage: "https://ysf-frappuccino.net/"
repository: "https://github.com/YumNumm/ysf-frappuccino"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.6
  email_validator: ^2.1.17
  envied: ^0.3.0+3
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mobile_scanner: ^3.3.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.1.1
  supabase_flutter: ^1.10.10

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  envied_generator: ^0.3.0+3
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.4
  json_serializable: ^6.7.1
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
